// @flow

// Network
export const ADD_PROVIDER = 'ADD_PROVIDER'
export const REMOVE_PROVIDER = 'REMOVE_PROVIDER'
export const ADD_ACCOUNT = 'ADD_ACCOUNT'
export const REMOVE_ACCOUNT = 'REMOVE_ACCOUNT'

export const NEW_CONTRACT_COMPILED = 'NEW_CONTRACT_COMPILED'
export const NEW_CONTRACT_DEPLOYED = 'NEW_CONTRACT_DEPLOYED'
export const NEW_CONTRACT_INSTANCE = 'NEW_CONTRACT_INSTANCE'
export const REMOVE_CONTRACT_INSTANCE = 'REMOVE_CONTRACT_INSTANCE'
export const CLEAR_CONTRACT_INSTANCE = 'CLEAR_CONTRACT_INSTANCE'
export const COMPILED_CONTRACT_CHANGED = 'COMPILED_CONTRACT_CHANGED'
export const GET_COMPILED_CONTRACTS = 'GET_COMPILED_CONTRACTS'

// Transactions
export const NEW_TRANSACTION_BROADCASTED = 'NEW_TRANSACTION_BROADCASTED'

// popup
export const DISPLAY_POPUP = 'DISPLAY_POPUP'
export const DISPLAY_POPUP_SUCCESS = 'DISPLAY_POPUP_SUCCESS'
export const DISPLAY_POPUP_FAILED = 'DISPLAY_POPUP_FAILED'

export const DISMISS_POPUP = 'DISMISS_POPUP'
export const DISMISS_POPUP_SUCCESS = 'DISMISS_POPUP_SUCCESS'
export const DISMISS_POPUP_FAILED = 'DISMISS_POPUP_FAILED'

export const DISPLAY_CONFIRM_MODAL = 'DISPLAY_CONFIRM_MODAL'
export const DISPLAY_ALERT_MODAL = 'DISPLAY_ALERT_MODAL'
