import {LibraryPlugin} from '@remixproject/engine'
import * as packageJson from '../package.json'
import React from 'react'
import SettingsUI from './components/settings'
import ContractDropdownUI from './components/contractDropdown'
import DropdownLogic from './components/dropdownlogic'
import InstanceContainer from './components/instanceContainer'

import * as $ from 'jquery'
import * as ethJSUtil from 'ethereumjs-util'
import Caver from 'caver-js'
import EventManager from './lib/events'

import css from './styles/run-tab-styles'
import UniversalDAppUI from './components/universal-dapp-ui'

const profile = {
	name: 'udapp',
	displayName: 'Deploy & run transactions',
	icon: 'data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0idXRmLTgiPz4NCjwhLS0gR2VuZXJhdG9yOiBBZG9iZSBJbGx1c3RyYXRvciAxNi4wLjAsIFNWRyBFeHBvcnQgUGx1Zy1JbiAuIFNWRyBWZXJzaW9uOiA2LjAwIEJ1aWxkIDApICAtLT4NCjwhRE9DVFlQRSBzdmcgUFVCTElDICItLy9XM0MvL0RURCBTVkcgMS4xLy9FTiIgImh0dHA6Ly93d3cudzMub3JnL0dyYXBoaWNzL1NWRy8xLjEvRFREL3N2ZzExLmR0ZCI+DQo8c3ZnIHZlcnNpb249IjEuMSIgaWQ9IkxheWVyXzFfY29weSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgeD0iMHB4Ig0KCSB5PSIwcHgiIHdpZHRoPSI3NDIuNTQ1cHgiIGhlaWdodD0iNjc2Ljg4NnB4IiB2aWV3Qm94PSIwIC0wLjIwNCA3NDIuNTQ1IDY3Ni44ODYiDQoJIGVuYWJsZS1iYWNrZ3JvdW5kPSJuZXcgMCAtMC4yMDQgNzQyLjU0NSA2NzYuODg2IiB4bWw6c3BhY2U9InByZXNlcnZlIj4NCjxnPg0KCTxwb2x5Z29uIHN0cm9rZT0iI0ZGRkZGRiIgc3Ryb2tlLW1pdGVybGltaXQ9IjEwIiBwb2ludHM9IjI5NS45MTEsMC43MTEgNDg4LjkxMSwzMDQuMTg2IDQ4OC45MTEsMzk3LjE4MSAyOTMuOTExLDY3Ni41NTYgDQoJCTc0MS43ODYsMzQ5Ljk0MyAJIi8+DQoJPHBvbHlnb24gc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiIHBvaW50cz0iNDE3LjA4Myw0MDYuNTg5IDIwOS43OTEsNTE5LjQ5NCAxLjg0Niw0MDYuMjM0IDIwOS43OTEsNjc1Ljg2MyAJIi8+DQoJPHBvbHlnb24gc3Ryb2tlPSIjRkZGRkZGIiBzdHJva2UtbWl0ZXJsaW1pdD0iMTAiIHBvaW50cz0iNDE3LjA4MywzMTguNzA3IDIwOS43OTEsMC43MTEgMS44NDYsMzE4LjQyOCAyMDkuNzkxLDQzMS42ODkgCSIvPg0KPC9nPg0KPC9zdmc+DQo=',
	description: 'execute and save transactions',
	kind: 'udapp',
	location: 'sidePanel',
	documentation: 'https://remix-ide.readthedocs.io/en/latest/run.html',
	version: packageJson.version,
	permission: true,
	events: ['newTransaction'],
	methods: ['createVMAccount', 'sendTransaction', 'getAccounts', 'pendingTransactionsCount'],
};

class LibraryExecutor extends LibraryPlugin {
	constructor(pluginUDapp) {
		super(pluginUDapp, profile);
	}

	render() {
		return <div />;
	}
}

class RunTab extends React.Component {
  constructor (props) {
    
    super(props)
    
    const { blockchain, pluginUDapp, config = {}, fileManager = {}, editor = {}, networkModule, fileProvider = {}, artefacts } = props
  
    this.event = new EventManager()
    this.config = config
    this.blockchain = blockchain
    this.fileManager = fileManager
    this.editor = editor
    this.logCallback = (msg) => { alert(msg) }
    this.compilersArtefacts = artefacts
    this.networkModule = networkModule
    this.fileProvider = fileProvider

    this.plugin = new LibraryExecutor(pluginUDapp)

    this.state = {
      contracts: []
    }

    blockchain.resetAndInit(config,{
      getAddress: (cb) => {
        cb(null, this.settings.txOrigin.value)
      },
      getValue: (cb) => {
        try {
          const number = document.querySelector('#value').value
          const select = document.getElementById('unit')
          const selectedUnit = select.value
          let unit = 'peb' // default
          if (['peb', 'gpeb', 'mklay', 'klay'].indexOf((selectedUnit || "").toLowerCase()) >= 0) {
            unit = selectedUnit
          }
          cb(null, Caver.utils.toPeb(number, unit))
        } catch (e) {
          cb(e)
        }
      },
      getGasLimit: (cb) => {
        try {
          cb(null, '0x' + new ethJSUtil.BN($('#gasLimit').val(), 10).toString(16))
        } catch (e) {
          cb(e.message)
        }
      }
    })

    this.dropdownLogic = new DropdownLogic(artefacts, config, editor, this.plugin)

    global.client.fileManager.on('currentFileChanged', function (fileName) {
      this.contractDropdownUI.changeCurrentFile(fileName)
    }.bind(this))
    
    // ----------------- compilation metadata generation servive ---------
    // this.compilerMetadata = new CompilerMetadata(blockchain, () => {  })
  }


  InstanceContainer = () => {
    return <div className={`${css.instanceContainer} border-0 list-group-item`}>
      <div className="d-flex justify-content-between align-items-center pl-2 ml-1 mb-2"
           title="Autogenerated generic user interfaces for interaction with deployed contracts">
        Deployed Contracts
        <i className={`mr-2 ${css.icon} far fa-trash-alt`} data-id="deployAndRunClearInstances"
           onClick={() => this.event.trigger('clearInstance', [])}
           title="Clear instances list and reset recorder" aria-hidden="true">
        </i>
      </div>
      {
        this.state.contracts.map(contract => {
          return <UniversalDAppUI abi={ contract.abi } address={ contract.address } contractName={ contract.name } />
        })
      }
      {
        this.state.contracts.length < 1 && <span className="mx-2 mt-3 alert alert-warning" data-id="deployAndRunNoInstanceText" role="alert">
        Currently you have no contract instances to interact with.
      </span>
      }
    </div>
  }
  
  render() {
    return (
      <div className="run-tab" id="runTabView" data-id="runTabView">
        <div className="list-group list-group-flush">
          <SettingsUI ref={ ref => this.settings = ref } blockchain={ this.blockchain } networkModule={ this.networkModule } />
          <ContractDropdownUI onLoad={ this.registerEvents } blockchain={ this.blockchain } dropdownLogic={ this.dropdownLogic } runView={ this } ref={ ref => this.contractDropdownUI = ref } />
          <InstanceContainer blockchain={ this.blockchain } />
        </div>
      </div>
    )
  }
}

export default RunTab;
